PROCESSED_DATA_FOLDER = r"data_sources\processed_data"
RAW_DATA_FILE = r"data_sources\raw_data\export.xml"
RAW_DATA_FOLDER = r"data_sources\raw_data"
MUSIC_JSON_FILE = r"data_sources\raw_data\today_music.json"
HEALTH_DATA_PROCESS = r"data_sources\processed_data\apple_health_export_processed_export.xml"